### ISSUE TITLE
Can you make tutorial video it hard understand everthing with text

### ISSUE THREAD

**Issue by ACMOIDRE** [aminblm/linkedin-application-bot#10]
Can you make tutorial video it hard understand everthing with text

**Comment by wodsuz** [comment]
Please refer to the original repo https://github.com/wodsuz/EasyApplyJobsBot this duplicate on doesn't get updates nor backed by our team

**Comment by aminblm** [comment]
The videos are to be purchased separately at the moment to cover development expenses.
