### ISSUE TITLE
Doesn't work with Firefox profile

### ISSUE THREAD

**Issue by IamPratikG** [aminblm/linkedin-application-bot#14]
The script doesn't work with a firefox profile

![image](https://github.com/aminblm/linkedin-application-bot/assets/30284688/185298e4-05a1-4736-b9e6-7509f3f93404)

**Comment by wodsuz** [comment]
Please refer to the original repo https://github.com/wodsuz/EasyApplyJobsBot this duplicate on doesn't get updates nor backed by our team
