### ISSUE TITLE
Do you own this repo?

### ISSUE THREAD

**Issue by tanerjn** [aminblm/linkedin-application-bot#15]
https://github.com/wodsuz/EasyApplyJobsBot

**Comment by alpersarac** [comment]
You can't own a repo, however you can clone or fork a repo

**Comment by tanerjn** [comment]
I can own a repo, everybody can own a repo. You can own a repo too, magic. I wondered who owns the main code.

**Comment by wodsuz** [comment]
Please refer to the original repo https://github.com/wodsuz/EasyApplyJobsBot this duplicate on doesn't get updates nor backed by our team
