### ISSUE TITLE
Fails to fill City

### ISSUE THREAD

**Issue by cohenaj194** [aminblm/linkedin-application-bot#16]
the City field should be pretty simple to fill but it is unable to do so

**Comment by alpersarac** [comment]
It has to be complete city name, for example: if you write Istanbul, it wouldn't be accepted. you should write Istanbul, Turkey instead. You can see the correct city value by searching your city in textbox.

**Comment by aminblm** [comment]
🚀 Hello team, I'm back at it! Any updates on this issue? Still a concern or resolved? Thanks for keeping me informed! ✌️
