### ISSUE TITLE
Blacklist keywords in title not working properly?

### ISSUE THREAD

**Issue by izhzz** [aminblm/linkedin-application-bot#19]
I have issues with the bot still applying for blacklisted keywords in the job title. Those keywords are not case sensitive and can stand anywhere in the title, right? E.g. I try to exclude "sales" but it still applies for positions with "sales" in the title.

**Comment by alpersarac** [comment]
Because it is not in use, there is no logic for blacklisting. It is basically for future development.

**Comment by wodsuz** [comment]
Please refer to the original repo https://github.com/wodsuz/EasyApplyJobsBot this duplicate on doesn't get updates nor backed by our team

**Comment by aminblm** [comment]
👋 Hey folks, I'm back on maintaining this. Is this issue still active? Any updates or fixes? Appreciate the heads up! 🙌
