### ISSUE TITLE
Add graphical interface and End-to-End integration

### ISSUE THREAD

**Issue by aminblm** [aminblm/linkedin-application-bot#2]
- [ ] From installation to running the script - have a graphical interface
  - [ ] Graphical configuration

**Comment by AVOCAVentures** [comment]
I will look into this after I debug my MacOS FF app opening twice after load

**Comment by wodsuz** [comment]
Please refer to the original repo https://github.com/wodsuz/EasyApplyJobsBot this duplicate on doesn't get updates nor backed by our team
