### ISSUE TITLE
Error in main: 'str' object has no attribute 'capabilities'

### ISSUE THREAD

**Issue by useradrian0000** [aminblm/linkedin-application-bot#21]
I get the next error when I try to launch Linkedin.py

Error in main: 'str' object has no attribute 'capabilities'
---Took: 0 minute(s).
Traceback (most recent call last):
  File "C:\Users\adrian\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "C:\Users\adrian\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 71, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

**Comment by bomzj** [comment]
Confirm, I have the same blocker.

**Comment by vignesh628** [comment]
Yes i faced the same

**Comment by Johra444** [comment]
same

**Comment by hsspratt** [comment]
Did anyone manage to fix this?

**Comment by bomzj** [comment]
> Did anyone manage to fix this?

@hsspratt Had to write my own LinkedIn bot instead :)

**Comment by PixelFireXY** [comment]
If you go to pull requests you can see the fix that if you have selenium above the 4.6.0 you don't need to add executable_url and in the latest version of Selenium you don't need to download webdriver.

**Comment by wodsuz** [comment]
Please refer to the original repo https://github.com/wodsuz/EasyApplyJobsBot this duplicate on doesn't get updates nor backed by our team

**Comment by aminblm** [comment]
Hey everyone, I resumed the maintenance on this, is this issue still of actuality, did a solution come up ? Thanks for the reporting!
