### ISSUE TITLE
value error 

### ISSUE THREAD

**Issue by garimaloh** [aminblm/linkedin-application-bot#22]
![image](https://github.com/aminblm/linkedin-application-bot/assets/48873678/87b4676e-a132-4857-a4fd-9b77a3284f30)
I am getting value error. Can anyone help me fix the url change for chrome driver?

**Comment by garimaloh** [comment]
Anybody going to address the issue?

**Comment by lustyun** [comment]
pip install --upgrade webdriver_manager
